database:
  port: 5432
  database_name: "kriegdercreator"
  username: "postgres"
  password: "password"
email_client:
  smtp_host: "TODO"
  sender_email: "TODO"
  sender_password: "TODO"
  timeout_milliseconds: 5000
